/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CapaPresentacion;

import CapaEntidades.Cliente;
import CapaNegocio.BancoServicios;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class Acceso_Cuentas extends javax.swing.JFrame {
    // Atributo para conectar con la capa de negocio
    private BancoServicios bancoServicios;

   
   public Acceso_Cuentas(BancoServicios bancoServicios) {
         // PRUEBA DE DIAGNÓSTICO
      java.net.URL test = getClass().getResource("/Imagenes/LOGO.png");
      System.out.println("Ruta imagen: " + test);  // null = imagen no encontrada

        this.bancoServicios = bancoServicios;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("ACCESO CUENTAS");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnVolverCuentas = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnIniciarSesionCliente = new javax.swing.JButton();
        btnRegistrate = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtUsuarioCliente = new javax.swing.JTextField();
        txtPasswordCliente = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1130, 750));

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(150, 208, 199));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("INGRESE SUS CREDENCIALES");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 197, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Usuario:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel7.setText("Contraseña:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        btnVolverCuentas.setText("Volver");
        btnVolverCuentas.addActionListener(this::btnVolverCuentasActionPerformed);
        jPanel4.add(btnVolverCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));
        
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGO.png"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 250, 160));

        btnIniciarSesionCliente.setBackground(new java.awt.Color(0, 102, 102));
        btnIniciarSesionCliente.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnIniciarSesionCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesionCliente.setText("Iniciar Sesión");
        btnIniciarSesionCliente.addActionListener(this::btnIniciarSesionClienteActionPerformed);
        jPanel4.add(btnIniciarSesionCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 287, 44));

        btnRegistrate.setBackground(new java.awt.Color(0, 102, 51));
        btnRegistrate.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrate.setText("Registrate !!");
        btnRegistrate.addActionListener(this::btnRegistrateActionPerformed);
        jPanel4.add(btnRegistrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 110, 20));

        jLabel9.setText("Si aún no tienes cuenta");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, -1, 10));

        txtUsuarioCliente.addActionListener(this::txtUsuarioClienteActionPerformed);
        jPanel4.add(txtUsuarioCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 287, 40));
        jPanel4.add(txtPasswordCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 290, 40));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 340, 500));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 380, 540));

        jPanel5.setBackground(new java.awt.Color(150, 208, 199));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("BIENVENIDO AL SISTEMA BANCARIO");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 380, 40));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/login_C.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioClienteActionPerformed

    private void btnVolverCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverCuentasActionPerformed
        PaginaPrincipal principal = new PaginaPrincipal(bancoServicios);
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverCuentasActionPerformed

    private void btnIniciarSesionClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionClienteActionPerformed
        String user = txtUsuarioCliente.getText().trim();
        String pass = new String(txtPasswordCliente.getPassword()).trim();

        if (user.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, llene todos los campos.", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            if (!bancoServicios.login(user, pass)) {
                JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Login OK: buscar el cliente por USUARIO (no por cédula)
            CapaEntidades.Cliente clienteActual = bancoServicios.obtenerClientePorUsuario(user);
            if (clienteActual == null) {
                JOptionPane.showMessageDialog(this, "Error interno: no se encontró el cliente.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Cada usuario está ligado a UNA sola cuenta: AHORROS o CORRIENTE
            String tipo = bancoServicios.getTipoCuentaAsociada(user);

            if ("AHORROS".equals(tipo)) {
                if (clienteActual.isBloqueadoAhorros()) {
                    JOptionPane.showMessageDialog(this,
                            "Su Cuenta de Ahorros ha sido bloqueada.\n"
                            + "Contacte al banco: 1800-BANCO-MIAU",
                            "Cuenta bloqueada", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                new Cta_Ahorros(bancoServicios, clienteActual).setVisible(true);

            } else if ("CORRIENTE".equals(tipo)) {
                if (clienteActual.isBloqueadoCorriente()) {
                    JOptionPane.showMessageDialog(this,
                            "Su Cuenta Corriente ha sido bloqueada.\n"
                            + "Contacte al banco: 1800-BANCO-MIAU",
                            "Cuenta bloqueada", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                new Cta_Corriente(bancoServicios, clienteActual).setVisible(true);

            } else {
                JOptionPane.showMessageDialog(this,
                        "Usuario no encontrado o sin cuenta asociada.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            this.dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnIniciarSesionClienteActionPerformed

    private void btnRegistrateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrateActionPerformed
        Registro_Clientes registro = new Registro_Clientes(bancoServicios);
        registro.setVisible(true);
        this.dispose();    }//GEN-LAST:event_btnRegistrateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesionCliente;
    private javax.swing.JButton btnRegistrate;
    private javax.swing.JButton btnVolverCuentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField txtPasswordCliente;
    private javax.swing.JTextField txtUsuarioCliente;
    // End of variables declaration//GEN-END:variables
}
