/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion;

import CapaEntidades.Cliente;
import CapaEntidades.Solicitud;
import CapaNegocio.BancoServicios;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class AperturarCuenta extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AperturarCuenta.class.getName());

    private BancoServicios bancoServicios;
    private Cliente clienteActual;

    /**
     * Creates new form AperturarCuenta
     */
    public AperturarCuenta() {
        initComponents();
    }

    /**
     * Constructor usado cuando se abre desde una sesión de cliente ya logueado
     * (botón "Aperturar" en Cta_Ahorros o Cta_Corriente). Precarga sus datos
     * personales en los campos de solo lectura del formulario.
     */
    public AperturarCuenta(BancoServicios bancoServicios, Cliente cliente) {
        this.bancoServicios = bancoServicios;
        this.clienteActual = cliente;
        initComponents();
        this.setLocationRelativeTo(null);
        precargarDatosCliente();
    }

    private void precargarDatosCliente() {
        if (clienteActual == null) {
            return;
        }
        txtCedula.setText(clienteActual.getCedula());
        txtNombre.setText(clienteActual.getNombre());
        txtApellido.setText(clienteActual.getApellido());
        txtCorreo.setText(clienteActual.getCorreo());
        txtTelefono.setText(clienteActual.getTelefono());
        txtEdad.setText(String.valueOf(clienteActual.getEdad()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuario5 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnVolverRegistro = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        btnRegistrarUsuario = new javax.swing.JButton();
        txtCorreo = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtUsuario1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtUsuario2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtUsuario3 = new javax.swing.JTextField();
        txtUsuario4 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtUsuario6 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPassword1 = new javax.swing.JPasswordField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel20.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel20.setText("Usuario:");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel21.setText("Contraseña:");

        jPassword.addActionListener(this::jPasswordActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 0, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel4.setText("Cédula:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel5.setText("Apellido:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, 30));

        btnVolverRegistro.setText("Volver");
        btnVolverRegistro.addActionListener(this::btnVolverRegistroActionPerformed);
        jPanel4.add(btnVolverRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("Aperturar Nueva Cuenta");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 420, 40));

        txtNombre.setEditable(false);
        jPanel4.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 470, 30));
        jPanel4.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 470, 30));

        btnRegistrarUsuario.setBackground(new java.awt.Color(102, 0, 102));
        btnRegistrarUsuario.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnRegistrarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarUsuario.setText("SOLICITAR");
        btnRegistrarUsuario.addActionListener(this::btnRegistrarUsuarioActionPerformed);
        jPanel4.add(btnRegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 680, 580, 44));

        txtCorreo.setEditable(false);
        txtCorreo.addActionListener(this::txtCorreoActionPerformed);
        jPanel4.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 470, 30));

        txtApellido.setEditable(false);
        jPanel4.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 470, 30));
        jPanel4.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 170, 30));

        txtEdad.setEditable(false);
        jPanel4.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 470, 30));

        txtTelefono.setEditable(false);
        jPanel4.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 470, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel7.setText("Nombre:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel8.setText("Correo:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel9.setText("Teléfono:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel10.setText("Edad:");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel14.setText("Ocupación:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, -1, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel18.setText("Tipo de Cuenta:");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, -1, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuenta Ahorros", "Cuenta Corriente" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);
        jPanel4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 630, 470, 30));
        jPanel4.add(txtUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 200, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel15.setText("Ingresos:");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, 30));
        jPanel4.add(txtUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 180, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel16.setText("Gastos:");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, -1, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel17.setText("Cargas Faminiares:");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, 30));
        jPanel4.add(txtUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 180, 30));
        jPanel4.add(txtUsuario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 410, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel19.setText("Dirección de residencia:");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 180, 40));

        txtUsuario6.setEditable(false);
        jPanel4.add(txtUsuario6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 590, 200, 30));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabel22.setText(" lo evidenciara en el siguiente apartado:");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 530, 20));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel23.setText("Contraseña:");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, -1, 30));

        jPassword1.addActionListener(this::jPassword1ActionPerformed);
        jPanel4.add(jPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 590, 200, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel24.setText("Usuario:");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, -1, 30));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabel25.setText("Ingrese su información personal de manera correcta, el banco verificara sus datos.");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 530, 20));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabel26.setText("A continuación ingrese una nueva contraseña para la nueva cuenta, debe tener en cuenta que el usuario se generara y");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 530, 20));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 690, 750));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 730, 790));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGO.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/login_A.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverRegistroActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverRegistroActionPerformed

    private void btnRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUsuarioActionPerformed
        if (clienteActual == null || bancoServicios == null) {
            JOptionPane.showMessageDialog(this,
                    "No hay una sesión de cliente activa para procesar esta solicitud.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String tipoCuenta = jComboBox1.getSelectedItem() != null
                ? jComboBox1.getSelectedItem().toString() : "Cuenta Ahorros";
        String ingresos = txtUsuario1.getText().trim();
        String gastos = txtUsuario2.getText().trim();
        String cargasFamiliares = txtUsuario3.getText().trim();
        String direccion = txtUsuario4.getText().trim();

        if (direccion.isEmpty() || ingresos.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Por favor, complete al menos la dirección y los ingresos.",
                    "Datos incompletos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // El cliente no puede pedir una cuenta que ya tiene activa
        boolean esCorriente = tipoCuenta.equals("Cuenta Corriente");
        if (esCorriente && clienteActual.isCuentaCorrienteActiva()) {
            JOptionPane.showMessageDialog(this,
                    "Usted ya dispone de una Cuenta Corriente activa.",
                    "Cuenta existente", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!esCorriente && clienteActual.isCuentaAhorrosActiva()) {
            JOptionPane.showMessageDialog(this,
                    "Usted ya dispone de una Cuenta de Ahorros activa.",
                    "Cuenta existente", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Generar credenciales nuevas y únicas para la cuenta solicitada
        String nuevoUsuario = bancoServicios.generarUsuarioUnico(clienteActual.getNombre(), clienteActual.getApellido());
        String nuevaPass = bancoServicios.generarPasswordSegura();

        // Mostrarlas en pantalla (solo lectura)
        txtUsuario6.setEditable(false);
        jPassword1.setEditable(false);
        txtUsuario6.setText(nuevoUsuario);
        jPassword1.setText(nuevaPass);

        // Asignar las credenciales a la cuenta correspondiente. Quedan
        // guardadas, pero la cuenta no es utilizable (isCuentaXActiva = false)
        // hasta que el área administrativa apruebe la solicitud.
        if (esCorriente) {
            clienteActual.configurarCredencialesCorriente(nuevoUsuario, nuevaPass);
        } else {
            clienteActual.setUsuario(nuevoUsuario);
            clienteActual.setContraseña(nuevaPass);
        }

        String detalle = "Solicitud de apertura: " + tipoCuenta
                + " | Ingresos: " + ingresos
                + " | Gastos: " + gastos
                + " | Cargas familiares: " + cargasFamiliares
                + " | Dirección: " + direccion
                + " | Usuario asignado: " + nuevoUsuario;

        Solicitud solicitud = new Solicitud(
                "APERTURA",
                clienteActual.getCedula(),
                clienteActual.getNombre() + " " + clienteActual.getApellido(),
                tipoCuenta, // se reutiliza este campo para saber qué cuenta se pidió
                0,
                detalle
        );

        bancoServicios.emitirSolicitud(solicitud);

        JOptionPane.showMessageDialog(this,
                "¡Solicitud enviada!\n\n"
                + "Su usuario para la " + tipoCuenta + " es: " + nuevoUsuario + "\n"
                + "No olvide su contraseña: la necesitará para ingresar una vez que "
                + "el área administrativa apruebe su solicitud.\n\n"
                + "El área administrativa la revisará y te notificará la decisión.",
                "Solicitud enviada", JOptionPane.INFORMATION_MESSAGE);

        this.dispose();
    }//GEN-LAST:event_btnRegistrarUsuarioActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassword1ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarUsuario;
    private javax.swing.JButton btnVolverRegistro;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JPasswordField jPassword1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtUsuario1;
    private javax.swing.JTextField txtUsuario2;
    private javax.swing.JTextField txtUsuario3;
    private javax.swing.JTextField txtUsuario4;
    private javax.swing.JTextField txtUsuario5;
    private javax.swing.JTextField txtUsuario6;
    // End of variables declaration//GEN-END:variables
}
