/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion;

import CapaNegocio.BancoServicios;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class Registro_Clientes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registro_Clientes.class.getName());

    /**
     * Creates new form Registro_Clientes
     */
    private BancoServicios bancoServicios;

    public Registro_Clientes(BancoServicios bancoServicios) {
        this.bancoServicios = bancoServicios;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnVolverRegistro = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        btnRegistrarUsuario = new javax.swing.JButton();
        txtCorreo = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPasswordConfirmar = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel11.setText("Cédula:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel12.setText("Nombre:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel13.setText("Apellido:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1130, 700));

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 0, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel4.setText("Cédula:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel5.setText("Apellido:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, 30));

        btnVolverRegistro.setText("Volver");
        btnVolverRegistro.addActionListener(this::btnVolverRegistroActionPerformed);
        jPanel4.add(btnVolverRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("REGISTRO DE DATOS");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 360, 40));
        jPanel4.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 470, 30));
        jPanel4.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 470, 30));

        btnRegistrarUsuario.setBackground(new java.awt.Color(102, 0, 102));
        btnRegistrarUsuario.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnRegistrarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarUsuario.setText("REGISTRARSE");
        btnRegistrarUsuario.addActionListener(this::btnRegistrarUsuarioActionPerformed);
        jPanel4.add(btnRegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 670, 580, 44));
        jPanel4.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 470, 30));
        jPanel4.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 470, 30));
        jPanel4.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 470, 30));
        jPanel4.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 470, 30));
        jPanel4.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 470, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel7.setText("Nombre:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel8.setText("Correo:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel9.setText("Teléfono:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel10.setText("Edad:");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel14.setText("Usuario:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel15.setText("Contraseña:");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, -1, 30));

        jPasswordConfirmar.addActionListener(this::jPasswordConfirmarActionPerformed);
        jPanel4.add(jPasswordConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, 470, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel16.setText("Contraseña:");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, -1, 30));

        jPassword.addActionListener(this::jPasswordActionPerformed);
        jPanel4.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 470, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel17.setText("Confirmar");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, -1, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel18.setText("Tipo de Cuenta:");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, -1, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuenta Ahorros", "Cuenta Corriente" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);
        jPanel4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 610, 470, 30));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 690, 750));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 730, 790));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGO.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/login_A.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUsuarioActionPerformed
        String cedula         = txtCedula.getText().trim();
        String nombre         = txtNombre.getText().trim();
        String apellido       = txtApellido.getText().trim();
        String correo         = txtCorreo.getText().trim();
        String telefono       = txtTelefono.getText().trim();
        String edadTxt        = txtEdad.getText().trim();

        // Credenciales de acceso (un solo usuario/contraseña para el cliente)
        String usuario  = txtUsuario.getText().trim();
        String pass     = new String(jPassword.getPassword()).trim();
        String pass2    = new String(jPasswordConfirmar.getPassword()).trim();

        // --- Campos obligatorios ---
        if (cedula.isEmpty() || nombre.isEmpty() || apellido.isEmpty()
                || usuario.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos obligatorios.",
                    "Campos incompletos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // --- Contraseñas coinciden ---
        if (!pass.equals(pass2)) {
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // --- Cédula: exactamente 10 dígitos numéricos ---
        if (!cedula.matches("\\d{10}")) {
            JOptionPane.showMessageDialog(this,
                    "La cédula debe tener exactamente 10 dígitos numéricos.",
                    "Cédula inválida", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // --- Edad ---
        int edad;
        try {
            edad = Integer.parseInt(edadTxt);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La edad debe ser un número entero.",
                    "Edad inválida", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (edad < 18) {
            JOptionPane.showMessageDialog(this,
                    "Debe ser mayor de edad (18 años o más) para registrarse.",
                    "Edad no permitida", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // --- Generar números de cuenta ---
        long ts = System.currentTimeMillis();
        String numAhorros   = "AHO-" + String.format("%06d", ts % 900000 + 100000);
        String numCorriente = "COR-" + String.format("%06d", (ts + 1) % 900000 + 100000);

        try {
            // El objeto Cliente siempre necesita ambos números de cuenta (lo exige su
            // constructor), pero según el "Tipo de Cuenta" elegido, solo UNA de las dos
            // queda realmente accesible: le damos las credenciales reales del usuario
            // solo a esa; a la otra le asignamos una identidad interna irrepetible que
            // el cliente nunca conocerá, así que nunca podrá iniciar sesión con ella.
            // En la práctica, solo la cuenta elegida queda "creada" para el cliente.
            String tipoCuentaSeleccionado = (String) jComboBox1.getSelectedItem();
            boolean esAhorros = tipoCuentaSeleccionado == null || tipoCuentaSeleccionado.equals("Cuenta Ahorros");

            String usuarioAhorros, passAhorros;
            String usuarioCorriente = null, passCorriente = null;

            if (esAhorros) {
                usuarioAhorros = usuario;
                passAhorros = pass;
            } else {
                usuarioAhorros = "_SIN_ACCESO_" + cedula;
                passAhorros = java.util.UUID.randomUUID().toString();
                usuarioCorriente = usuario;
                passCorriente = pass;
            }

            CapaEntidades.Cliente nuevo = new CapaEntidades.Cliente(
                    cedula, nombre, apellido, correo, telefono, edad,
                    usuarioAhorros, passAhorros, numAhorros, numCorriente
            );
            if (usuarioCorriente != null) {
                nuevo.configurarCredencialesCorriente(usuarioCorriente, passCorriente);
            }

            // Marca cuál cuenta queda realmente disponible para el cliente.
            // (bloqueadoAhorros/bloqueadoCorriente quedan en false por defecto:
            // eso es solo para la función de "bloquear tarjeta", no para esto).
            nuevo.setCuentaAhorrosActiva(esAhorros);
            nuevo.setCuentaCorrienteActiva(!esAhorros);

            // Enviar SOLICITUD al área administrativa (no crea la cuenta todavía)
            String detalle = String.format(
                "Cédula: %s | Correo: %s | Teléfono: %s | Edad: %d | Cuenta solicitada: %s",
                cedula, correo, telefono, edad, tipoCuentaSeleccionado
            );
            bancoServicios.solicitarNuevoRegistro(nuevo, detalle);

            // Mensaje al cliente
            JOptionPane.showMessageDialog(this,
                    " Su solicitud de registro ha sido enviada al área administrativa.\n\n"
                    + "Será notificado por correo a: " + correo + "\n"
                    + "cuando su cuenta haya sido aprobada y pueda acceder al sistema.\n\n"
                    + "Cédula: " + cedula + "\n"
                    + "Usuario asignado: " + usuario + "\n"
                    + "Tipo de cuenta: " + tipoCuentaSeleccionado,
                    "Solicitud enviada", JOptionPane.INFORMATION_MESSAGE);

            // Volver al login
            new Acceso_Cuentas(bancoServicios).setVisible(true);
            this.dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),
                    "Error en el registro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarUsuarioActionPerformed

    private void jPasswordConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordConfirmarActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void btnVolverRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverRegistroActionPerformed
        Acceso_Cuentas login = new Acceso_Cuentas(bancoServicios);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverRegistroActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarUsuario;
    private javax.swing.JButton btnVolverRegistro;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JPasswordField jPasswordConfirmar;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
